### ISSUE TITLE
Implement custom theming support

### ISSUE THREAD

**Issue by AyanamiRei1** [DasAmpharos/EonTimer#25]
I wanted to fork this and make a dark version but I'm unable to build it for this reason
![image](https://user-images.githubusercontent.com/25233407/61166931-4bc82f80-a52e-11e9-8540-3e0074eae9da.png)
 
And I have no idea why if you know why this happening please let me know.

Thanks.

**Comment by dylmeadows** [comment]
The dependencies were hosted with a personal maven repository and I have been in the process of migrating those to being hosted at https://oss.jfrog.com. Planning on updating master here soon with the changes.

**Comment by AyanamiRei1** [comment]
Oh alrighty btw about my dark theme it's just a big ol' CSS edit and a new picture.

**Comment by dylmeadows** [comment]
Yeah I downloaded it and extracted the contents of the JAR to see the changes. The theme looks really good! I’ll create a feature request for custom theming to track progress on it and ping you when the mechanism for selecting the theme is finalized. We can add your theme as a separate CSS file that can be selected in the UI.

**Comment by AyanamiRei1** [comment]
I'd have a go at it but I haven't got a clue about Java FX or Java just a little bit of CSS.

**Comment by AyanamiRei1** [comment]
Oh btw this happens when EonTimer breaks 
[error.txt](https://github.com/dylmeadows/EonTimer/files/3412493/error.txt)

![image](https://user-images.githubusercontent.com/25233407/61560925-8f0e2b00-aa65-11e9-900f-2102bcfd5113.png)

**Comment by dylmeadows** [comment]
That error is really weird. NullPointerExceptions are notorious for killing Java applications. Has that happened again since you commented last?

**Comment by AyanamiRei1** [comment]
Yeah it's happened haven't got a clue why and this happens without my edited one.

**Comment by AyanamiRei1** [comment]
@dylmeadows Update the bug doesn't happen if visual is turned off.

**Comment by dylmeadows** [comment]
So it's happening when the visual cue is flashing? Is it getting out of sync and staying colored in after the timer has stopped?

**Comment by AyanamiRei1** [comment]
That exactly
