### ISSUE TITLE
Minutes before target should be 1 when target seconds is equal to 1 or 2

### ISSUE THREAD

**Issue by remokon** [DasAmpharos/EonTimer#28]
Hi, I was doing some gen 5 RNG and I noticed that when target seconds are set to 0 or 1 minutes before target is still 0 instead of being 1.
I'm using v2.0.1

Cheers and thank you very much for the much better EonTimer ;)

**Comment by DasAmpharos** [comment]
@remokon I'm going to close this. I recently rewrote the application in python with PySide6 and this was fixed during the rewrite. You can find the alpha release artifacts [here](https://github.com/DasAmpharos/EonTimer/releases/tag/3.0.0-alpha.1)
