### ISSUE TITLE
How do you even run this

### ISSUE THREAD

**Issue by Leosh11** [DasAmpharos/EonTimer#30]
i, as a total noob, don't understand how to run this program. i can't find a .exe and therefore am totally unable to start it for lack of knowledge, anyone has a idea how to do it?

**Comment by dylmeadows** [comment]
Requires Oracle JRE 8 (https://www.oracle.com/java/technologies/javase-jre8-downloads.html). After you unzip the zip file from the releases tab on GitHub there is a bin folder inside the unzip folder. On Windows, you'll double click the `EonTimer.bat` file. If on Linux or macOS it's the `EonTimer` file.

**Comment by dylmeadows** [comment]
Working on a way to make running the application easier. Java screwed over their developers with a change they made a few years ago. There's been a lot of confusion around getting the application running. Still tuned for updates and stuff.

**Comment by Leosh11** [comment]
thank you for the answer, appreciate that. yeah i didn't know that the .bat started the program (maybe put that into the readme?)

**Comment by Leosh11** [comment]
this might be a longshot buuut... i keep hitting this, 6004ms it the right delay for i'am targeting 02002 and a SEED of E60A1786... how do i get 23 seconds instead of 24? i would appreciate the help if possible
![desktop](https://user-images.githubusercontent.com/62500760/77356157-1246f580-6d46-11ea-94bd-649e83a36d43.PNG)

**Comment by dylmeadows** [comment]
Np

**Comment by Conor-Don** [comment]
hello, i do not understand as to how to get this to run on my Windows laptop. im completely confused and i was hoping that someone could help me out?

**Comment by Leosh11** [comment]
@Conor-Don so basicially you install the Java Runtime https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html and than you click on Eontimer.bin in the bin folder and than it's open and you just follow the video

**Comment by jojobobb** [comment]
@Leosh11 which java program do i install because the link brings you to the java website and there are a bunch of programs to download. Do i download all of them?

**Comment by Leosh11** [comment]
nah brah just windows whatever version you have

**Comment by jojobobb** [comment]
Thanx for responding!
