### ISSUE TITLE
Adding an icon for Windows, Mac and Linux releases

### ISSUE THREAD

**Issue by AyanamiRei1** [DasAmpharos/EonTimer#68]
Prehaps for 3.0.1

**Comment by dylmeadows** [comment]
I'm fine with sneaking this into 3.0.0. New version, slightly new look, might as well include an icon while we are at it :)

**Comment by dylmeadows** [comment]
Icon is designed and added to documentation. Further work is required to add the icon to the application itself.

**Comment by DasAmpharos** [comment]
Fixed in #100
