### ISSUE TITLE
Just requesting the artifacts from the most recent 3.0.0 test build.

### ISSUE THREAD

**Issue by ShilohBeeler** [DasAmpharos/EonTimer#85]
Using macOS to try to run 2.0.1, no matter what I try I get java errors. When I get past the javafx issue by using a version of java that has fx bundled, I still get the error: "Error: Could not find or load main class io.github.dylmeadows.eontimer.AppLauncher". I saw in other closed issues a link to a test build of 3.0.0, but it looks like all the artifacts have been deleted since the test build was run over 6 months ago.

Thanks for your time and your help!

**Comment by dylmeadows** [comment]
I'll run another build so the artifacts repopulate. I'll message you when it's ready

**Comment by dylmeadows** [comment]
The macOS portion of the build is failing, so I'm going to need to look at the CI/CD pipeline this weekend to figure that out. I'll keep you updated in this thread.

**Comment by ShilohBeeler** [comment]
Sounds good. Thanks for looking into it, I really do appreciate it!

**Comment by DasAmpharos** [comment]
@ShilohBeeler I'm going to close this since it's no longer relevant. I recently rewrote the application in python with PySide6. You can find the alpha release artifacts [here](https://github.com/DasAmpharos/EonTimer/releases/tag/3.0.0-alpha.1)
