### ISSUE TITLE
Open to Sponsor?

### ISSUE THREAD

**Issue by AndrewRedican** [DasAmpharos/EonTimer#86]
Hi there,

I'd like to sponsor open source project on Github.

Pokemon has a special place in my heart as I played many of these games when I was a child. I think this is really cool coding project and I'd like to show my support by giving some amount monthly, at least enough to get a fancy latte.

**Comment by dylmeadows** [comment]
Hey there!

That's a great idea and I wouldn't mind setting that up. I've been busy lately with big life changes (moving / wife is pregnant) so I would feel bad being supported for something I don't have a ton of time to maintain. Once things settle down a little bit then I can set that up. It would help too if I wanted to develop an Android/iOS version. Publishing apps for mobile requires some money to register as a developer for each app store.

I'll post updates here.

**Comment by DasAmpharos** [comment]
I'm going to go ahead and close this. I don't mind doing the work for free for now 😅 I may revisit this in the future but I'm fine with things the way they are currently
