### ISSUE TITLE
add eontimer 3 to releases 

### ISSUE THREAD

**Issue by sakuraglitch** [DasAmpharos/EonTimer#87]
can somebody add eontimer 3.0 to releases? i got banned from blisys server (didn't even do anything bad) so i can't get the link.

**Comment by dylmeadows** [comment]
@sakuraglitch what operating system are you on?

**Comment by FinocchiaroGR** [comment]
Hello, I have an MacBook Pro with BigSur, I have attempted to build the dmg for the version 3.0, but when I open it it doesn't work any of the buttons.. not sure if you can provide me with the 3.0 release, cause I tried to use on the build, a EonTimer custom background that doesnt actually works on my computer.

**Comment by sakuraglitch** [comment]
pretty sure eontimer doesnt work on mac

**Comment by ElLorans** [comment]
still no 3.0 release? I don't know from where to download the latest one. Is it the 2.0.1?

**Comment by DasAmpharos** [comment]
@sakuraglitch @FinocchiaroGR @ElLorans I'm going to close this since it's no longer relevant. I recently rewrote the application in python with PySide6. You can find the alpha release artifacts [here](https://github.com/DasAmpharos/EonTimer/releases/tag/3.0.0-alpha.1)
