### ISSUE TITLE
cant run on mac after updating java

### ISSUE THREAD

**Issue by genshi12345** [DasAmpharos/EonTimer#88]
[EonTimer.log](https://github.com/dylmeadows/EonTimer/files/6633539/EonTimer.log)

here is the log file

error message 

Error: Could not find or load main class io.github.dylmeadows.eontimer.AppLauncher
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
logout

**Comment by PetitJean27** [comment]
I have exactly the same error on my mac.
I have Java 8 Update 301 and my mac version is 10.13.6.

**Comment by nicoleesposito** [comment]
Having this same issue. Running Catalina 10.15.17 with the latest java.

**Comment by DasAmpharos** [comment]
@genshi12345 @PetitGens @nicoleesposito I'm going to close this since it's no longer relevant. I recently rewrote the application in python with PySide6. You can find the alpha release artifacts [here](https://github.com/DasAmpharos/EonTimer/releases/tag/3.0.0-alpha.1)
