### ISSUE TITLE
EonTimer.bat does nothing

### ISSUE THREAD

**Issue by GitHUBAlex1** [DasAmpharos/EonTimer#89]
When I open the .bat file it appears to open a CMD window, then closes it and nothing happens. I'm in Windows 10 64bit ASUS if it helps.

**Comment by Diabolo-kun** [comment]
The same thing happens to me, I tried to update my java to sound the alarm and when I got it, it didn't work

**Comment by Asrour494** [comment]
Have the same problem, but only on my desktop. Have tried uninstalling and reinstalling separately for JDK and JRE several times. However, my laptop works just fine with no issues

**Comment by DasAmpharos** [comment]
@GitHUBAlex1 @Diabolo-kun @Asrour494 I'm going to close this since it's no longer relevant. I recently rewrote the application in python with PySide6. You can find the alpha release artifacts [here](https://github.com/DasAmpharos/EonTimer/releases/tag/3.0.0-alpha.1)
