### ISSUE TITLE
EonTimer's timing notifications are late

### ISSUE THREAD

**Issue by FunhouseFactory** [DasAmpharos/EonTimer#90]
i have zero idea on how to fix it but both the audio and visual markers are off-time, they start and end late. i've messed around with the timing of the beeps/visual thing as well as just deleting and reinstalling and nothing has fixed it yet

first time ever using github (made an account just for this) so forgive me if i mess this up somehow

**Comment by DasAmpharos** [comment]
@FunhouseFactory I know this is an old issue, but can you try with the latest release and see if the problem is still persisting for you?

**Comment by DasAmpharos** [comment]
If not then I'm going to close this issue due to inactivity
