### ISSUE TITLE
Cannot Get in EonTimer

### ISSUE THREAD

**Issue by Dusk74** [DasAmpharos/EonTimer#93]
Hey there. I tried to download the EonTimer with the Lati Twins but it won't exactly let me run it. What's going on?

**Comment by DasAmpharos** [comment]
@Dusk74 I'm going to close this since it's no longer relevant. I recently rewrote the application in python with PySide6. You can find the alpha release artifacts [here](https://github.com/DasAmpharos/EonTimer/releases/tag/3.0.0-alpha.1)
