### ISSUE TITLE
Error while lunching bat luncher : Could not find or load main class io.github.dylmeadows.eontimer.AppLauncher

### ISSUE THREAD

**Issue by mattgomes2001** [DasAmpharos/EonTimer#96]
I downloaded the zip file provided and here is what I got when I try to lunch the bat file... what should I do ?

**Comment by DasAmpharos** [comment]
@mattgomes2001 @lazy-val I'm going to close this since it's no longer relevant. I recently rewrote the application in python with PySide6. You can find the alpha release artifacts [here](https://github.com/DasAmpharos/EonTimer/releases/tag/3.0.0-alpha.1)
